### PR TITLE
ASM-5170 Fix for recursive alias when transport is required multiple times

### PR DESCRIPTION
**Pull request by asaenz**
This is the fix that @ripienaar suggested.  @ksw2599 tested and it seemed to be working.

### CODE REVIEW

**Comment by ripienaar** [comment]
Thanks, I can't merge the other one due to perms

**Comment by gavin-scott** [comment]
Looks like the puppet transport one has a fix that @asaenz put in that isn't in this file. I think we should delete this file out to avoid confusion over which transport is getting used.

**Comment by aimers1975** [comment]
@gavin-scott Can you review and merge or let us know if there is more work?

**Comment by aimers1975** [comment]
@gavin-scott nevermind, was confused because the other PR related to this is still open.

**Pull request merged**
